### ISSUE TITLE
repair genomes before creating alignment

### ISSUE THREAD

**Issue by mcolpus** [rrwick/Verticall#5]
Hi Ryan,

I have an alignment I've made with snippy. But some of my genomes contain ambiguous bases so Verticall requires them to be repaired. Should I rerun snippy to make a new alignment first?

Thanks!

**Comment by rrwick** [comment]
Your assemblies will need to be repaired for Verticall, but you should be able to leave your Snippy alignment as it is. In fact, your assemblies shouldn't be relevant for your Snippy - that should just based on your reads and your reference genome.

The one caveat to this is that your reference genome must be complete and free of ambiguous bases. If that's not the case, then yes, you'll need to fix (or replace) it and then re-run Snippy.

Ryan

**Comment by vsanchez0** [comment]
Hi @rrwick, I am running Verticall on some samples and was wondering what I should do given that my reference is flagged as having ambiguous bases. Is the best strategy to just choose a new reference and regenerate my alignment?

**Comment by rrwick** [comment]
Since you're talking about a reference and an alignment, I assume you're doing the [alignment tree workflow](https://github.com/rrwick/Verticall/wiki/Alignment-tree-workflow). In which case, yes, an unambiguous reference sequence is required. So you would need to disambiguate your reference sequence (replace all ambiguous bases with canonical bases) using another genome to determine what the bases should be, or just choose a new reference without ambiguous bases. And then regenerate the alignment and rerun Verticall.

If you instead wanted to do the [distance tree workflow](https://github.com/rrwick/Verticall/wiki/Distance-tree-workflow), no special reference is needed. You can treat your reference genome like any other assembly (and process it with [Verticall repair](https://github.com/rrwick/Verticall/wiki/Verticall-repair)) or leave it out entirely.

Ryan
